Add a sanity test for circular imports. (#1030)
# Description

<!--
Thank you for contributing to Oumi! Before sending your PR out for
review, please take a quick read through this template.

When your PR is merged, its title will appear in our release notes. Make
sure your title gives a clear description of your change!

After you've updated your title, please replace this section with a
detailed description of your change. Include as much context as possible
so your reviewers can easily understand *what* you're changing and
*why*.
The more information you provide, the faster we can review your change!
-->
<!--↓↓↓↓↓↓↓↓↓↓ Describe your change below ↓↓↓↓↓↓↓↓↓↓-->
This test finds every `*.py` file under `/src/oumi/...`, then loads each
file in a separate test. Any circular dependencies will manifest as
ImportErrors.

Current output:
```
FAILED tests/integration/deps/test_circular_deps.py::test_load_py_files[oumi.judge] - AssertionError: Error loading oumi.judge. Exitcode: 1
FAILED tests/integration/deps/test_circular_deps.py::test_load_py_files[oumi.core.datasets.base_sft_dataset] - AssertionError: Error loading oumi.core.datasets.base_sft_dataset. Exitcode: 1
FAILED tests/integration/deps/test_circular_deps.py::test_load_py_files[oumi.core.datasets.base_pretraining_dataset] - AssertionError: Error loading oumi.core.datasets.base_pretraining_dataset. Exitcode: 1
FAILED tests/integration/deps/test_circular_deps.py::test_load_py_files[oumi.core.datasets.base_iterable_dataset] - AssertionError: Error loading oumi.core.datasets.base_iterable_dataset. Exitcode: 1
FAILED tests/integration/deps/test_circular_deps.py::test_load_py_files[oumi.core.datasets.packed_sft_dataset] - AssertionError: Error loading oumi.core.datasets.packed_sft_dataset. Exitcode: 1
FAILED tests/integration/deps/test_circular_deps.py::test_load_py_files[oumi.core.datasets.base_map_dataset] - AssertionError: Error loading oumi.core.datasets.base_map_dataset. Exitcode: 1
FAILED tests/integration/deps/test_circular_deps.py::test_load_py_files[oumi.core.datasets.base_dpo_dataset] - AssertionError: Error loading oumi.core.datasets.base_dpo_dataset. Exitcode: 1
FAILED tests/integration/deps/test_circular_deps.py::test_load_py_files[oumi.core.datasets.vision_language_dataset] - AssertionError: Error loading oumi.core.datasets.vision_language_dataset. Exitcode: 1
FAILED tests/integration/deps/test_circular_deps.py::test_load_py_files[oumi.core.datasets.pretraining_async_text_dataset] - AssertionError: Error loading oumi.core.datasets.pretraining_async_text_dataset. Exitcode: 1
FAILED tests/integration/deps/test_circular_deps.py::test_load_py_files[oumi.core.trainers.oumi_trainer] - AssertionError: Error loading oumi.core.trainers.oumi_trainer. Exitcode: 1
FAILED tests/integration/deps/test_circular_deps.py::test_load_py_files[oumi.core.trainers.base_trainer] - AssertionError: Error loading oumi.core.trainers.base_trainer. Exitcode: 1
FAILED tests/integration/deps/test_circular_deps.py::test_load_py_files[oumi.core.trainers.hf_trainer] - AssertionError: Error loading oumi.core.trainers.hf_trainer. Exitcode: 1
FAILED tests/integration/deps/test_circular_deps.py::test_load_py_files[oumi.inference.vllm_inference_engine] - AssertionError: Error loading oumi.inference.vllm_inference_engine. Exitcode: 1
FAILED tests/integration/deps/test_circular_deps.py::test_load_py_files[oumi.inference.remote_vllm_inference_engine] - AssertionError: Error loading oumi.inference.remote_vllm_inference_engine. Exitcode: 1
FAILED tests/integration/deps/test_circular_deps.py::test_load_py_files[oumi.inference.llama_cpp_inference_engine] - AssertionError: Error loading oumi.inference.llama_cpp_inference_engine. Exitcode: 1
FAILED tests/integration/deps/test_circular_deps.py::test_load_py_files[oumi.inference.sglang_inference_engine] - AssertionError: Error loading oumi.inference.sglang_inference_engine. Exitcode: 1
FAILED tests/integration/deps/test_circular_deps.py::test_load_py_files[oumi.inference.anthropic_inference_engine] - AssertionError: Error loading oumi.inference.anthropic_inference_engine. Exitcode: 1
FAILED tests/integration/deps/test_circular_deps.py::test_load_py_files[oumi.inference.native_text_inference_engine] - AssertionError: Error loading oumi.inference.native_text_inference_engine. Exitcode: 1
FAILED tests/integration/deps/test_circular_deps.py::test_load_py_files[oumi.inference.remote_inference_engine] - AssertionError: Error loading oumi.inference.remote_inference_engine. Exitcode: 1
FAILED tests/integration/deps/test_circular_deps.py::test_load_py_files[oumi.inference.gcp_inference_engine] - AssertionError: Error loading oumi.inference.gcp_inference_engine. Exitcode: 1
=========================================================================== 20 failed, 161 passed, 1 warning in 372.56s (0:06:12) ==========================================================================
```

I'll work towards resolving these broken tests as a follow up (this is
the real issue).
<!--↑↑↑↑↑↑↑↑↑↑ Describe your change above ↑↑↑↑↑↑↑↑↑↑-->

## Related issues

<!--
Make sure to list any relevant related issues to your change. More often
than not this will be the single issue fixed by your PR.
-->
<!--↓↓↓↓↓↓↓↓↓↓ List your related issues below ↓↓↓↓↓↓↓↓↓↓-->

Towards OPE-836

<!--↑↑↑↑↑↑↑↑↑↑ List your related issues above ↑↑↑↑↑↑↑↑↑↑-->

## Before submitting

- [ ] This PR only changes documentation. (You can ignore the following
checks in that case)
- [x] Did you read the [contributor
guideline](https://github.com/oumi-ai/oumi/blob/main/CONTRIBUTING.md)
Pull Request guidelines?
- [x] Did you link the issue(s) related to this PR in the section above?
- [x] Did you add / update tests where needed?

## Reviewers

At least one review from a member of `oumi-ai/oumi-staff` is required.

<!-- Add `oumi-ai/oumi-staff` as a reviewer when your PR is ready for
review.

You are also welcome to add individual members of `oumi-ai/oumi-staff`
as reviewers.

If no one has reviewed your PR after several days, feel free to add a
comment tagging specific reviewers.

 -->